apache/incubator-seata-website

docs/zh-cn/architecture/fescar_at.md
docs/zh-cn/overview/what_is_fescar.md

Signed-off-by: jimin.jm <jimin.jm@alibaba-inc.com>

fix #14 update fescar-at undo_log sql script

---

docs/zh-cn/quickstart/api.md

https://github.com/seata/seata.github.io/blob/master/docs/zh-cn/quickstart/api.md bug fixed

add api.md bug fixed

---

index.html

add go import

---

docs/en-us/user/quickstart.md

Fix quickstart.md code Format error

Fix quickstart.md code Format error

---

docs/zh-cn/user/quickstart.md

Translation (zh-cn)quickstart.md

Translation (zh-cn)quickstart.md

---

docs/en-us/user/api.md
site_config/docs.js

Migrate api guide docs from repo https://github.com/seata/awesome-seata  #33

Migrate api guide docs from repo https://github.com/seata/awesome-seata 

---

docs/en-us/user/microservice.md
site_config/docs.js

Migrate microservices framework supports docs from repo https://github.com/seata/awesome-seata #33

Migrate (en-us) microservices framework supports docs from repo https://github.com/seata/awesome-seata

---

docs/zh-cn/user/microservice.md

Migrate (zh-cn) microservices framework supports docs from repo https://github.com/seata/awesome-seata #33

Migrate (zh-cn) microservices framework supports docs from repo https://github.com/seata/awesome-seata 

---

blog/en-us/download.md
site_config/site.js

(en-us) Add download pageMenu And Add download.md #34

(en-us) Add download pageMenu And Add download.md

---

blog/zh-cn/download.md
site_config/site.js

(zh-cn) Add download pageMenu And Add download.md  #34

(zh-cn) Add download pageMenu And Add download.md

---

site_config/home.js
site_config/site.js

transfer : (en-us)home page by zh-cn

transfer : (en-us)home page by zh-cn

---

site_config/home.js

update what is seata? - introduction

update what is seata? - introduction

---

docs/en-us/developers/contributor-guide/new-contributor-guide_dev.md
docs/zh-cn/developers/contributor-guide/new-contributor-guide_dev.md

update new-contributor-guide_dev.md - Reporting issue

update new-contributor-guide_dev.md - reporting issue

---

docs/zh-cn/ops/deploy-guide-beginner.md
site_config/docs.js

add deploy-guide-beginner

---

docs/en-us/overview/terminology.md

bugfix:fix TM typo

---

docs/en-us/dev/mode/at-mode.md
docs/en-us/overview/what-is-seata.md

translation : (en-us)what-is-seata.md

---

docs/en-us/overview/faq.md
docs/zh-cn/overview/faq.md

optimize:
1.Add a list of questions and anchor points for faq.md.
2.Add a new qa.
After optimization, readers can quickly locate the QA.

optimize:Add a list of questions and anchor points for faq.md

---

docs/en-us/dev/mode/at-mode.md
docs/en-us/dev/mode/saga-mode.md
docs/en-us/dev/mode/tcc-mode.md
docs/en-us/dev/seata-mertics.md
docs/en-us/developers/committer-guide/label-an-issue-guide_dev.md
docs/en-us/developers/committer-guide/website-guide_dev.md
docs/en-us/developers/contributor-guide/new-contributor-guide_dev.md
docs/en-us/developers/contributor-guide/reporting-security-issues_dev.md
docs/en-us/developers/contributor-guide/test-coverage-guide_dev.md
docs/en-us/developers/developers_dev.md
docs/en-us/developers/guide_dev.md
docs/en-us/ops/deploy-server.md
docs/en-us/ops/multi-configuration-isolation.md
docs/en-us/overview/faq.md
docs/en-us/overview/terminology.md
docs/en-us/overview/what-is-seata.md
docs/en-us/user/api.md
docs/en-us/user/microservice.md
docs/en-us/user/quickstart.md

add SEO header for (en-us).md file

---

docs/zh-cn/user/saga.md

Saga docs add Repository APIs

---

blog/en-us/download.md

Add historical en-us release notes

---

docs/zh-cn/user/saga.md
saga_designer/vedio.html

Provide a vedio tutorial of Saga statemachine designer

Provide a vedio tutorial of Saga statemachine designer

---

docs/zh-cn/ops/config-center.md

remove useless words

---

baidu_verify_VZ2B9aerrE.html

verify website

---

blog/en-us/download.md

fix 1.2.0 release notes

---

docs/zh-cn/user/configurations.md

Supplement db mode maxWait parameter description

add db mode maxWait parameter description

---

blog/en-us/download.md
blog/zh-cn/download.md

add release notes for 1.3.0

---

site_config/community.jsx

add contact info

---

docs/en-us/developers/developers_dev.md
docs/zh-cn/developers/developers_dev.md

add committer info

---

docs/zh-cn/overview/faq.md

fixes https://github.com/seata/seata/issues/3194

faq 25: fix word 'sring' to 'spring'

---

blog/zh-cn/seata-datasource-proxy.md
site_config/blog.js

添加了一篇新的博客，主要介绍Seata数据源代理实现原理及使用时可能会遇到的问题

add a new blog of DataSourceProxy

---

docs/en-us/overview/faq.md
docs/zh-cn/overview/faq.md

add support frameworks in tcc mode

add support frameworks in tcc mode

---

blog/en-us/download.md
blog/zh-cn/download.md
docs/zh-cn/ops/upgrade.md
docs/zh-cn/user/configuration/nacos.md
docs/zh-cn/user/registry/nacos.md

fix the contributor's account name

fix the contributor's account name

---

docs/zh-cn/user/configurations.md

optimize: add doc about jdbc connection recommend 

---

site_config/home.js

add seata-golang button

---

blog/zh-cn/seata-config-manager.md
blog/zh-cn/seata-datasource-proxy.md
site_config/blog.js

添加了一篇新博客，详细介绍介绍Seata配置管理的核心实现以及和Spring配置的交互过程

add a new blog of seata-config-manager

---

blog/zh-cn/seata-dsproxy-deadlock.md

dsproxy deadlock

---

blog/en-us/download.md
blog/zh-cn/download.md
site_config/home.js

add 1.4.1 en/zh-cn release notes

---

blog/zh-cn/seata-client-start-analysis-01.md
blog/zh-cn/seata-client-start-analysis-02.md
site_config/blog.js

add seata-client-start-analysis docs

docs: add seata-client-start-analysis docs

---

docs/zh-cn/user/apm/skywalking.md
site_config/docs.js

https://github.com/seata/seata/pull/3652

support apm with skywalking

---

site_config/site.js

add summer 2021

---

sitemap.xml

add website map

---

docs/zh-cn/overview/faq.md

update FAQ "Could not found branch session"

---

docs/zh-cn/user/configuration/index.md
docs/zh-cn/user/configuration/nacos.md
docs/zh-cn/user/registry/eureka.md
docs/zh-cn/user/registry/index.md
docs/zh-cn/user/registry/nacos.md

完善eureka注册中心的文档

---

site_config/home.jsx

add who's using seata

---

docs/zh-cn/overview/faq.md

add Faq 27-30

---

docs/zh-cn/overview/faq.md
docs/zh-cn/user/configuration/apollo.md
docs/zh-cn/user/configuration/nacos.md
docs/zh-cn/user/registry/eureka.md
docs/zh-cn/user/registry/nacos.md

format faq.md and update seata-server config link

format faq.md and update seata-server config link

---

docs/en-us/overview/faq.md
docs/zh-cn/ops/deploy-ha.md
docs/zh-cn/overview/faq.md

Update docs/en-us/overview/faq.md and format docs/zh-cn/overview/faq.md

Update docs/en-us/overview/faq.md and format docs/zh-cn/overview/faq.md

---

docs/zh-cn/user/appendix/sqlreference/dml.md
site_config/docs.js

add catalogue

---

docs/zh-cn/user/configuration/nacos.md

optimize signal dataId for nacos document

---

docs/zh-cn/user/appendix/global-transaction-status.md

钉钉群里遇到有同学不清楚global_table里的状态码TimeoutRollbacking的含义，我希望增加些补充描述

Add description for global status TimeoutRollbacking

---

site_config/community.jsx

update contact us

---

docs/en-us/developers/developers_dev.md
docs/zh-cn/developers/developers_dev.md

update developer dev

---

docs/en-us/overview/faq.md
docs/zh-cn/overview/faq.md

doc: add faq

---

docs/zh-cn/user/registry/nacos.md
docs/zh-cn/user/txgroup/transaction-group-and-ha.md

add tips and fix a typo

---

docs/zh-cn/developers/contributor-guide/new-contributor-guide_dev.md

Ⅰ. Describe what this PR did
Ⅱ. Does this pull request fix one issue?
fixes #394
Ⅲ. Why don't you add test cases (unit test/integration test)?
Ⅳ. Describe how to verify it
Ⅴ. Special notes for reviews

bugfix：fix GitHub Issues link 404

---

docs/zh-cn/ops/deploy-by-docker-compose.md
docs/zh-cn/ops/deploy-by-docker.md
site_config/docs.js

1.docker-compose【单机模式】、【nacos注册中心db模式】、【多实例高可用模式】等多种部署seata-server方式
2.补充db模式下相应的建表sql语句
3.补充注册中心配置示例、配置中心配置示例

add detailed docker-compose deployment seata-server

---

docs/zh-cn/user/registry/etcd3.md

feat: add etcd3 registry document

---

docs/zh-cn/user/configurations.md

fix: change asynCommitBufferLimit to asyncCommitBufferLimit

---

docs/zh-cn/user/registry/consul.md

Fixes #397 add document using consul as the registry

feat: add document using consul as the registry

---

site_config/community.jsx
site_config/site.js

add SEATA IN CLOUD navigation

---

docs/zh-cn/user/configuration/consul.md

feat: add document using consul as the config center

---

saga_designer/index.html

optimize: optimize saga_designer/index.html

---

saga_designer/index.html

update saga_designer/index.html 

---

docs/zh-cn/developers/contributor-activity/top-contributer_dev.md

Modify link as hyperlink

---

docs/zh-cn/dev/seata-mertics.md

bugfix: update the document of metrices

bugfix: update the document of metrices

---

docs/zh-cn/user/appendix/global-transaction-status.md

https://github.com/seata/seata/pull/4391#issuecomment-1043926147

add global status

---

docs/zh-cn/dev/seata-mertics.md

Fix errors in seata-metrics document

Fix errors in seata-metrics document

---

docs/en-us/developers/contributor-guide/test-coverage-guide_dev.md
docs/en-us/developers/developers_dev.md
docs/en-us/ops/deploy-by-docker.md
docs/en-us/ops/deploy-by-kubernetes.md
docs/en-us/overview/faq.md
docs/en-us/overview/what-is-seata.md
docs/en-us/user/quickstart.md
docs/zh-cn/dev/seata-mertics.md
docs/zh-cn/developers/contributor-guide/new-contributor-guide_dev.md
docs/zh-cn/developers/contributor-guide/test-coverage-guide_dev.md
docs/zh-cn/developers/developers_dev.md
docs/zh-cn/ops/config-center.md
docs/zh-cn/ops/deploy-by-docker.md
docs/zh-cn/ops/deploy-by-kubernetes.md
docs/zh-cn/ops/deploy-guide-beginner.md
docs/zh-cn/ops/deploy-server.md
docs/zh-cn/ops/operation.md
docs/zh-cn/overview/what-is-seata.md
docs/zh-cn/user/configurations.md
docs/zh-cn/user/configurations090.md
docs/zh-cn/user/datasource.md
docs/zh-cn/user/ormframework.md
docs/zh-cn/user/quickstart.md

update master markdown

---

docs/en-us/dev/mode/at-mode.md
docs/en-us/overview/what-is-seata.md

bugfix:Fix word spelling errors

---

site_config/site.js

update seata in cloud url

---

docs/zh-cn/ops/deploy-by-docker-142.md

update deploy-by-docker.md  1.5.0

---

blog/en-us/download.md
blog/zh-cn/download.md
site_config/home.jsx

add 1.5.1 release notes (zh-cn/en-us)

add 1.5.1 release notes

---

site_config/site.js

add navigation url

---

docs/zh-cn/ops/upgrade.md

optimize upgrade doc

---

site_config/site.js

update navigation url

---

blog/zh-cn/seata-tcc-fence.md

《阿里 Seata 新版本终于解决了 TCC 模式的幂等、悬挂和空回滚问题》增加博客头

seata-tcc-fence add header

---

blog/en-us/download.md
blog/zh-cn/download.md
blog/zh-cn/seata-tcc-fence.md
site_config/home.jsx

update 1.5.2 release Notes

---

site_config/home.jsx

update antfin logo

---

docs/en-us/ops/deploy-by-kubernetes.md

update Kubernetes for Seata

---

template.ejs

add google analytics

---

docs/zh-cn/ops/deploy-by-docker-compose.md

fix typo in deploy-by-docker-compose

---

template.ejs

add statistic for website

---

404.html
redirect.ejs
template.ejs

fix js.cookie.min.js load pending 

---

template.ejs

optimize statistic js

---

.github/workflows/license-checker.yaml
.licenserc.yaml
saga_designer/dist/bundle.js.map
saga_designer/index.html
saga_designer/vedio.html
template.ejs

add license checker

---

README.md
docsite.config.yml

optimize keywords

---

blog/en-us/download.md
blog/zh-cn/download.md
site_config/home.jsx

add 1.6.0 release notes

---

docs/zh-cn/ops/upgrade.md

add upgrade 1.6.0 notice

---

docs/zh-cn/ops/upgrade.md
site_config/home.jsx

upgrade to latest version

---

docsite.config.yml

fix the problem of Baidu search page traffic decline
fix #502

optimize SEO keywords

---

.github/workflows/license-checker.yaml
.licenserc.yaml
saga_designer/index.html
saga_designer/vedio.html
template.ejs

remove copyright header for SEO

---

site_config/site.js

add recruitment

---

.github/workflows/deploy-oss.yml

bugfix: fix docs content rollback during deployment

---

.github/workflows/deploy.yml

bugfix: add *.txt *.xml in deploy-dist

---

.github/workflows/deploy-oss.yml

bugfix: fix deploy-dist not exist

---

.htaccess

optimize: add etag

---

.github/workflows/deploy-oss.yml
.github/workflows/deploy.yml

optimize: deploy to OSS every 12 hours

---

docs/en-us/developers/developers_dev.md
docs/zh-cn/developers/developers_dev.md

optimize: update developers_dev.md

---

sitemap.xml

optimize: update sitemap.xml

---

robots.txt

optimize: add robots.txt

---

docs/en-us/developers/developers_dev.md
docs/zh-cn/developers/developers_dev.md

optimize: fix search engine get url dead link

---

site_config/site.js

optimize: optimize spider grab content

---

site_config/site.js

optimize: optimize microservice support doc

---

site_config/site.js

optimize: optimize site.js

---

src/pages/documentation/index.scss

close [#562](https://github.com/seata/seata.github.io/issues/562)

bugfix: fix incomplete document display #562

---

template.ejs

optimize: upgrade microservice landscape support en-us

---

blog/zh-cn/seata-tcc.md

optimize: fix tcc suspension desc error

---

.github/workflows/deploy-oss.yml
.github/workflows/deploy.yml

optimize: update workflow runner label

---

template.ejs

optimize SCA in microservice landscape

optimize: optimize SCA in microservice landscape

---

blog/zh-cn/seata-go-1.2.0.md
site_config/blog.js

add seata-go 1.2.0 release notes

add seata-go 1.2.0 release notes

---

blog/en-us/download.md
blog/zh-cn/download.md
site_config/home.jsx
site_config/site.js

doc: add release notes 

---

404.html
CNAME
LICENSE
robots.txt

optimize: add some files

---

src/pages/home/users/index.scss

bugfix: fix user logo style issues

---

i18n/en/code.json
i18n/zh-cn/code.json
src/pages/home/feature/index.tsx

optimize: update home page information

---

i18n/en/docusaurus-plugin-content-docs/version-v1.8.json
i18n/en/docusaurus-plugin-content-docs/version-v2.0.json
i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.8.json
i18n/zh-cn/docusaurus-plugin-content-docs/version-v2.0.json

optimize: fix version label

---

docusaurus.config.js

optimize: add baidu script

---

.github/workflows/deploy-oss.yml
robots.txt

新生成的sitemap为index形式，为了保证与老版本一致，这里直接将明细sitemap（sitemap.0.xml）改名后作为整体的sitemap，如果以后条数更多，明细sitemap会拆分为多个文件（sitemap.0.xml，sitemap.1.xml），届时可能需要修改.
The new generated sitemap for the index form, in order to ensure consistency with the old version, here directly to the details of the sitemap (sitemap.0.xml) renamed as a whole sitemap, if the number of articles in the future, the details of the sitemap will be split into multiple files  (sitemap.0.xml,sitemap.1.xml), you may need to modify.
XXXXX

optimize: optimize sitemap

---

package-lock.json
package.json

upgrade got dependency
fix #703 
upgrade got dependency

optimize: upgrade got dependency

---

docusaurus.config.js

optimize topbar display
optimize topbar display

optimize: optimize topbar display

---

baiduLinkSubmit.js

optimize: optimize baidu link submit workflow

---

baiduLinkSubmit.js

bugfix: fix baidu link submit "getaddrinfo ENOTFOUND" error

---

i18n/en/docusaurus-plugin-content-docs/current/user/registry/nacos.md
i18n/en/docusaurus-plugin-content-docs/version-v1.8/user/registry/nacos.md
i18n/en/docusaurus-plugin-content-docs/version-v2.0/user/registry/nacos.md
i18n/zh-cn/docusaurus-plugin-content-docs/current/user/registry/nacos.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-v1.8/user/registry/nacos.md
i18n/zh-cn/docusaurus-plugin-content-docs/version-v2.0/user/registry/nacos.md

optimize nacos registry doc
optimize nacos registry doc

doc: optimize nacos registry doc

---

docusaurus.config.js
src/pages/index.tsx

optimize: optimize the official homepage description and add keywords

---

docusaurus.config.js
src/pages/home/msemap/index.tsx

optimize: optimize some js to load on demand

---

.asf.yaml
.github/workflows/deploy-oss.yml
.github/workflows/deploy.yml

add ASF basic config
add ASF basic config

optimize: add ASF basic config

---

.asf.yaml

format asf.yaml
format asf.yaml

optimize: format asf.yaml

---

.github/workflows/deploy.yml

optimize: optimize ASF workflow

---

.asf.yaml
.github/workflows/deploy.yml

fix asf.yaml parser error
fix asf.yaml parser error
fix #738 

optimize: fix asf.yaml parser error

---

docs/zh-cn/dev/domain/overviewDomainModel.md

typos about overviewDomainModel docs
关于overviewDomainModel 文档的拼写错误
typos about overviewDomainModel docs
关于overviewDomainModel 文档的拼写错误

typos about overviewDomainModel docs
